version: '3'

services:
  python:
    image: python:3.7.0
    volumes:
      - /d/python:/root/api-gateway
    working_dir: /root/api-gateway
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
